Algoritmo "paridade"

Var
   n1:  inteiro
   n2: inteiro

Inicio
      escreval ("Digite o primeiro número: ")
      leia (n1)
      escreval ("Digite o segundo número: ")
      leia (n2)
      
      se (n1 > n2) entao
         escreval ("O primeiro número é maior!")
      senao
           se (n1 < n2) entao
              escreval ("O segundo número é maior!")
           senao
              escreval ("Os números apresentados têm o mesmo valor!")

      fimSe
      fimSe

Fimalgoritmo