algoritmo "semnome"
var
   dolar, reais, cotacao : real
   
inicio
      // Digite um numero de quantos reais você gostaria de comprar em dolar
      Escreva ("Quantos reais você gostaria de comprar? ")
      //Quantidade do dolar
      Leia( dolar)
      //Valor do real
      reais <- 0.20
      //cotação
      cotacao <- dolar / reais
      // Quantos reais você comprou em dolar
      escreva (" Com", dolar ," dolares você comprou ", cotacao, "reais")
      
fimalgoritmo