algoritmo "semnome"
var
  n1, a, b, negativo, positivo: real
inicio
      //Digite um numero para saber se ele é negativo ou positivo
      escreva ("digite um numero")
      leia (n1)
      // se caso o numero for negativo ele sera declarado  na variavel A
      a <- negativo - n1
      // se caso o numero for positivo ele sera declarado na variavel B
      b <- positivo + n1
     escreva (" a letra B é positivo ", b)
     escreva (" a letra A é negativo ", a)
      
fimalgoritmo